export const ITEM_ADDED = 'itemAdded';
export const QUANTITY_CHANGED = 'quantityChanged';
export const REMOVE_ITEM = 'removeItem';
export const EDIT_ITEM = 'editItem';
export const IS_ADDED = 'isAdded';
export const ORDER_ADDED = 'orderAdded';
export const ORDER_PRICE_CHANGED = 'orderPriceChanged';
export const SUBMITTED = 'submitted';
export const ORDER_DELIVERED = 'orderDelivered';
export const SALES_UPDATE = 'salesUpdate';
export const GET_TOTAL_SALES = 'getTotalSales';
export const LOAD_ITEMS = 'loadItems'; // Get Items From Database
export const LOAD_PENDING_ORDERS = 'loadPendingOrders'; // Get Pending Orders From Database
export const LOAD_DELIVERED_ORDERS = 'loadDeliveredOrders'; // Get Delivered Orders From Database
export const ADD_TO_DELIVERED = 'addToDelivered';
export const CANCEL_ORDER = 'cancelOrder';
export const ADD_NEW_ITEM = 'addNewItem';
export const DELETE_ITEM = 'deleteItem';
export const GET_CATEGORIES = 'getCategories';
export const ADD_CATEGORIES = 'addCategories';
export const DELETE_CATEGORIES = 'deleteCategories';
export const EDIT_CATEGORY = 'editCategory';
